name: Docker Image CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag jyu78749/ccctfx:latest
        - name: Save the Docker image
          run: docker save -o ccctfx-latest.tar jyu78749/ccctfx:latest
        - name: Upload tar to artifact
          uses: actions/upload-artifact@v1
          with:
            name: Docker Image
            path: ccctfx-latest.tar